name: Build and Test Model Explorer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            vcpkgCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
          - os: ubuntu-latest
            vcpkgCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
        vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
        vcpkgJsonGlob: '**/vcpkg.json'
        runVcpkgInstall: true

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Generate build files with CMake
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build Model Explorer
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build --output-on-failure
